{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oracle-trader.fullname" . }}-secrets
  namespace: {{ .Values.namespace | default "oracle-trader" }}
  labels:
    {{- include "oracle-trader.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database credentials
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  
  {{- if .Values.exchanges.binance.enabled }}
  # Binance API credentials
  BINANCE_API_KEY: {{ .Values.exchanges.binance.apiKey | default "your-binance-api-key" | quote }}
  BINANCE_SECRET_KEY: {{ .Values.exchanges.binance.secretKey | default "your-binance-secret" | quote }}
  {{- end }}
  
  {{- if .Values.exchanges.coinbase.enabled }}
  # Coinbase API credentials
  COINBASE_API_KEY: {{ .Values.exchanges.coinbase.apiKey | default "your-coinbase-api-key" | quote }}
  COINBASE_SECRET_KEY: {{ .Values.exchanges.coinbase.secretKey | default "your-coinbase-secret" | quote }}
  COINBASE_PASSPHRASE: {{ .Values.exchanges.coinbase.passphrase | default "your-coinbase-passphrase" | quote }}
  {{- end }}
  
  {{- if .Values.exchanges.kraken.enabled }}
  # Kraken API credentials
  KRAKEN_API_KEY: {{ .Values.exchanges.kraken.apiKey | default "your-kraken-api-key" | quote }}
  KRAKEN_SECRET_KEY: {{ .Values.exchanges.kraken.secretKey | default "your-kraken-secret" | quote }}
  {{- end }}
{{- end }}