apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle-trader.fullname" . }}
  namespace: {{ .Values.namespace | default "oracle-trader" }}
  labels:
    {{- include "oracle-trader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "oracle-trader.selectorLabels" . | nindent 4 }}