# AI Configuration for Oracle Trader Bot

# Global AI settings
ai_enabled: true
gpu_enabled: false  # Set to true if CUDA available
model_version: "1.0.0"

# Model paths
models_path: "/app/models"
trained_models_path: "/app/models/trained"
model_configs_path: "/app/models/configs"

# API Keys (set via environment variables)
alpha_vantage_api_key: "${ALPHA_VANTAGE_API_KEY}"
news_api_key: "${NEWS_API_KEY}"
finnhub_api_key: "${FINNHUB_API_KEY}"
twitter_bearer_token: "${TWITTER_BEARER_TOKEN}"
reddit_client_id: "${REDDIT_CLIENT_ID}"
reddit_client_secret: "${REDDIT_CLIENT_SECRET}"

# Model ensemble weights
ensemble_weights:
  lstm: 0.4
  transformer: 0.4
  ensemble: 0.2

# Prediction settings
default_prediction_horizon: 24  # hours
confidence_threshold: 0.7
max_predictions_per_request: 100

# Sentiment analysis
sentiment_sources:
  - news
  - twitter
  - reddit
  - telegram

# News collection
news_sources:
  - alpha_vantage
  - newsapi
  - finnhub
  - coindesk
  - cointelegraph

tracked_symbols:
  - BTC
  - ETH
  - ADA
  - SOL
  - MATIC
  - AVAX
  - AAPL
  - MSFT
  - GOOGL
  - TSLA
  - NVDA

# MLflow tracking
mlflow_tracking_uri: "http://mlflow:5000"
mlflow_experiment_name: "oracle_trader_ai"

# Model training schedules
training_schedule:
  lstm_retrain_hours: 168  # Weekly
  transformer_retrain_hours: 168  # Weekly
  rl_retrain_hours: 24  # Daily
  sentiment_model_retrain_hours: 72  # Every 3 days

# Performance monitoring
performance_thresholds:
  min_prediction_accuracy: 0.7
  max_acceptable_loss: 0.1
  min_confidence_score: 0.6

# Risk management
risk_limits:
  max_position_size: 0.8
  max_daily_trades: 100
  stop_loss_threshold: 0.05