# app/schemas/market_regime_schemas.py
from pydantic import BaseModel
from typing import Optional, List, Dict, Any, Literal

class MarketRegimeInfo(BaseModel):
    """
    Detailed information about the determined market regime.
    """
    trend_direction: Optional[Literal["UP", "DOWN", "SIDEWAYS"]] = "SIDEWAYS"
    trend_strength_adx: Optional[float] = None # ADX value
    is_trending: bool = False # True if ADX > trend_threshold
    is_strongly_trending: bool = False # True if ADX > strong_trend_threshold

    volatility_level: Optional[Literal["LOW", "NORMAL", "HIGH"]] = "NORMAL"
    bbw_value: Optional[float] = None # Bollinger Band Width value

    # Optional: Direct DI values if strategies need them without re-accessing dataframe
    plus_di: Optional[float] = None
    minus_di: Optional[float] = None

    # A human-readable summary label generated by the analysis function
    descriptive_label: str = "UNCERTAIN" 

class OHLCVWithIndicatorsAndRegimeResponse(BaseModel):
    """
    Response model for the endpoint that returns OHLCV data with indicators
    and detailed market regime information.
    """
    market_regime: MarketRegimeInfo # Using the detailed regime info schema
    data: List[Dict[str, Any]]    # The list of candlestick data with indicators
