# app/schemas/trading_signal.py
from pydantic import BaseModel, Field # <--- Field اینجا import شده است
from typing import Optional
from datetime import datetime, timezone # timezone برای datetime.now(timezone.utc)

# ما از TradeDirection که قبلاً در مدل‌های پایگاه داده تعریف کردیم، دوباره استفاده می‌کنیم
# مطمئن شوید که مسیر import صحیح است
from app.models.trade import TradeDirection # یا هر جایی که TradeDirection Enum شما تعریف شده است

class TradingSignal(BaseModel):
    """
    Represents a trading signal generated by a strategy.
    """
    symbol: str                     
    direction: TradeDirection         
    
    entry_price: Optional[float] = None                                     
    stop_loss: float                  
    take_profit: Optional[float] = None 
    
    suggested_leverage: int = 1       
    signal_strength: Optional[float] = None 
    
    strategy_name: str                
    trigger_price: Optional[float] = None 
    # استفاده صحیح از Field با default_factory برای مقداردهی اولیه زمان به UTC
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Config:
        from_attributes = True